### ISSUE TITLE
add dependencies group

### ISSUE THREAD

**Issue by shihyuho** [softleader/repository-package-manager#1]
`package.yaml` 的 dependencies 可選擇要或不要分組 (不支援部分分組), 不分組就跟現有模式一樣, 分組最多一層, yaml 檔就會寫成:

```yaml
name: softleader-azalea-roster-cli
version: 1.0.0
description: SoftLeader Azalea for CKI
dependencies:
  gateway:
  - softleader/softleader-azalea-roster-cki: ^v1.0.21
  setting:
  - softleader-product/softleader-setting-insurer-rpc: v1.1.0
  - softleader-product/softleader-setting-system-param-rpc: v1.1.0
  - softleader-product/softleader-setting-announce-rpc: v1.1.0
  - softleader-product/softleader-setting-high-risk-rpc: v1.1.0
  - softleader-product/softleader-setting-channel-rpc: v1.1.1
  - softleader-product/softleader-setting-occupation-rpc: v1.1.0
  - softleader-product/softleader-setting-public-file-rpc: v1.1.1
  security:
  - softleader-product/softleader-security-user-role-mapping-rpc: v1.1.1
  - softleader-product/softleader-security-channel-hierarchy-rpc: v1.1.2
  - softleader-product/softleader-security-role-rpc: v1.1.1
  - softleader-product/softleader-security-channel-rpc: v1.1.1
  - softleader-product/softleader-security-user-rpc: v1.1.0
filtering:
  - TAG: '${tag}'
```

在 node 中可以用 dependencies 為 array => 不分, object => 分 來判斷是否分組:

```javascript
{ name: 'softleader-azalea-roster-cli',
  version: '1.0.0',
  description: 'SoftLeader Azalea for CKI',
  dependencies: 
   { gateway: [ { 'softleader/softleader-azalea-roster-cki': '^v1.0.21' } ],
     setting: 
      [ { 'softleader-product/softleader-setting-insurer-rpc': 'v1.1.0' },
        { 'softleader-product/softleader-setting-system-param-rpc': 'v1.1.0' },
        { 'softleader-product/softleader-setting-announce-rpc': 'v1.1.0' },
        { 'softleader-product/softleader-setting-high-risk-rpc': 'v1.1.0' },
        { 'softleader-product/softleader-setting-channel-rpc': 'v1.1.1' },
        { 'softleader-product/softleader-setting-occupation-rpc': 'v1.1.0' },
        { 'softleader-product/softleader-setting-public-file-rpc': 'v1.1.1' } ],
     security: 
      [ { 'softleader-product/softleader-security-user-role-mapping-rpc': 'v1.1.1' },
        { 'softleader-product/softleader-security-channel-hierarchy-rpc': 'v1.1.2' },
        { 'softleader-product/softleader-security-role-rpc': 'v1.1.1' },
        { 'softleader-product/softleader-security-channel-rpc': 'v1.1.1' },
        { 'softleader-product/softleader-security-user-rpc': 'v1.1.0' } ] },
  filtering: [ { TAG: '${tag}' } ] }
```

完整安裝 `rpm install` 或指定檔案內容 `rpm install -c Containerfile` 安裝, 都會依照群組產生子目錄:

```
.
├── package.yaml
└── repositories
    ├── gateway
    │   └── softleader-azalea-roster-cki
    │       └── Containerfile
    ├── security
    │   ├── softleader-security-channel-hierarchy-rpc
    │   │   └── Containerfile
    │   ├── softleader-security-channel-rpc
    │   │   └── Containerfile
    │   ├── softleader-security-role-rpc
    │   │   └── Containerfile
    │   ├── softleader-security-user-role-mapping-rpc
    │   │   └── Containerfile
    │   └── softleader-security-user-rpc
    │       └── Containerfile
    └── setting
        ├── softleader-setting-announce-rpc
        │   └── Containerfile
        ├── softleader-setting-channel-rpc
        │   └── Containerfile
        ├── softleader-setting-high-risk-rpc
        │   └── Containerfile
        ├── softleader-setting-insurer-rpc
        │   └── Containerfile
        ├── softleader-setting-occupation-rpc
        │   └── Containerfile
        ├── softleader-setting-public-file-rpc
        │   └── Containerfile
        └── softleader-setting-system-param-rpc
            └── Containerfile
```
